### ISSUE TITLE
Different log levels depending on caller

### ISSUE THREAD

**Issue by drevell** [ngmoco/timber#6]
Like log4j, it would be nice to be able to configure different log levels for different parts of a program. In a large complicated program, it's sometimes necessary to enable debug logging for only one subsystem without spamming the logs with debug messages from every other subsystem. For example, in a webapp you might only want to enable debug logging for the code that validates incoming requests, without enabling any other debug output.

This is different than the ability to configure a log level for each output, which doesn't fulfill the need I'm thinking of.

This ability is similar to log4j's ability to configure different "loggers" for different classes/packages: http://logging.apache.org/log4j/2.x/manual/configuration.html , search for "logger". We could do something similar based on the filename returned from runtime.Caller(), such as determining the log level based on a prefix of the filename.

**Comment by smw1218** [comment]
Interesting... it looks like they separate "logger" vs "appender" where logger is something with a matcher, level and an appender. An appender is a destination to write to (file, socket etc).  The matcher matches class string but in our case it would be file path.  It's been a long time since I looked at log4j proper so this is just from a glance at the confs.

Sounds like it might be a pretty big refactor but I don't think it would be too hard.  I've been needing to give this lib some love.  Do you want to help out with a pull request?

**Comment by drevell** [comment]
I would love to code this, but realistically I'm not going to be able to make time for it in the near future. :disappointed:

**Comment by smw1218** [comment]
Added!

**Comment by drevell** [comment]
:+1: :dancer: :+1:
